export enum RequestName {
  GET_IMAGES = 'GET IMAGES',
  GET_IMAGES_BY_USERID = 'GET IMAGES BY USERID',
  GET_IMAGE_ENTITY = 'GET IMAGE ENTITY',
  UPDATE_IMAGE_ENTITY = 'UPDATE IMAGE ENTITY',
  CREATE_IMAGE_ENTITY = 'CREATE IMAGE ENTITY',
  DELETE_IMAGE_ENTITY = 'DELETE IMAGE ENTITY',
}

export type RequestError = {
  requestName: RequestName,
  error: string,
};

export type ImageData = {
  id?: number,
  link: string,
  userId: string,
};

export type ImagesDataState = {
  images: ImageData[],
  details: ImageData | null,
  loadingRequests: RequestName[],
  requestErrors: RequestError[],
};

export const GET_IMAGES_REQUEST = 'GET IMAGES REQUEST';
export const GET_IMAGES_SUCCESS = 'GET IMAGES SUCCESS';
export const GET_IMAGES_FAIL = 'GET IMAGES FAIL';
export const GET_IMAGES_BY_USERID_REQUEST = 'GET IMAGES BY USERID REQUEST';
export const GET_IMAGES_BY_USERID_SUCCESS = 'GET IMAGES BY USERID SUCCESS';
export const GET_IMAGES_BY_USERID_FAIL = 'GET IMAGES BY USERID FAIL';
export const GET_IMAGE_ENTITY_REQUEST = 'GET IMAGE ENTITY REQUEST';
export const GET_IMAGE_ENTITY_SUCCESS = 'GET IMAGE ENTITY SUCCESS';
export const GET_IMAGE_ENTITY_FAIL = 'GET IMAGE ENTITY FAIL';
export const UPDATE_IMAGE_ENTITY_REQUEST = 'UPDATE IMAGE ENTITY REQUEST';
export const UPDATE_IMAGE_ENTITY_SUCCESS = 'UPDATE IMAGE ENTITY SUCCESS';
export const UPDATE_IMAGE_ENTITY_FAIL = 'UPDATE IMAGE ENTITY FAIL';
export const CREATE_IMAGE_ENTITY_REQUEST = 'CREATE IMAGE ENTITY REQUEST';
export const CREATE_IMAGE_ENTITY_SUCCESS = 'CREATE IMAGE ENTITY SUCCESS';
export const CREATE_IMAGE_ENTITY_FAIL = 'CREATE IMAGE ENTITY FAIL';
export const DELETE_IMAGE_ENTITY_REQUEST = 'DELETE IMAGE ENTITY REQUEST';
export const DELETE_IMAGE_ENTITY_SUCCESS = 'DELETE IMAGE ENTITY SUCCESS';
export const DELETE_IMAGE_ENTITY_FAIL = 'DELETE IMAGE ENTITY FAIL';
export const CLEAR_IMAGES_DATA_STATE = 'CLEAR IMAGES DATA STATE';
export const CLEAR_IMAGE_ENTITY_STATE = 'CLEAR IMAGE ENTITY STATE';
