export enum RequestName {
  GET_LOGOS = 'GET LOGOS',
  GET_LOGOS_BY_USERID = 'GET LOGOS BY USERID',
  GET_LOGO_ENTITY = 'GET LOGO ENTITY',
  UPDATE_LOGO_ENTITY = 'UPDATE LOGO ENTITY',
  CREATE_LOGO_ENTITY = 'CREATE LOGO ENTITY',
  DELETE_LOGO_ENTITY = 'DELETE LOGO ENTITY',
}

export type RequestError = {
  requestName: RequestName,
  error: string,
};

export type LogoData = {
  id?: number,
  link: string,
  userId: string,
};

export type LogosDataState = {
  logos: LogoData[],
  details: LogoData | null,
  loadingRequests: RequestName[],
  requestErrors: RequestError[],
};

export const GET_LOGOS_REQUEST = 'GET LOGOS REQUEST';
export const GET_LOGOS_SUCCESS = 'GET LOGOS SUCCESS';
export const GET_LOGOS_FAIL = 'GET LOGOS FAIL';
export const GET_LOGOS_BY_USERID_REQUEST = 'GET LOGOS BY USERID REQUEST';
export const GET_LOGOS_BY_USERID_SUCCESS = 'GET LOGOS BY USERID SUCCESS';
export const GET_LOGOS_BY_USERID_FAIL = 'GET LOGOS BY USERID FAIL';
export const GET_LOGO_ENTITY_REQUEST = 'GET LOGO ENTITY REQUEST';
export const GET_LOGO_ENTITY_SUCCESS = 'GET LOGO ENTITY SUCCESS';
export const GET_LOGO_ENTITY_FAIL = 'GET LOGO ENTITY FAIL';
export const UPDATE_LOGO_ENTITY_REQUEST = 'UPDATE LOGO ENTITY REQUEST';
export const UPDATE_LOGO_ENTITY_SUCCESS = 'UPDATE LOGO ENTITY SUCCESS';
export const UPDATE_LOGO_ENTITY_FAIL = 'UPDATE LOGO ENTITY FAIL';
export const CREATE_LOGO_ENTITY_REQUEST = 'CREATE LOGO ENTITY REQUEST';
export const CREATE_LOGO_ENTITY_SUCCESS = 'CREATE LOGO ENTITY SUCCESS';
export const CREATE_LOGO_ENTITY_FAIL = 'CREATE LOGO ENTITY FAIL';
export const DELETE_LOGO_ENTITY_REQUEST = 'DELETE LOGO ENTITY REQUEST';
export const DELETE_LOGO_ENTITY_SUCCESS = 'DELETE LOGO ENTITY SUCCESS';
export const DELETE_LOGO_ENTITY_FAIL = 'DELETE LOGO ENTITY FAIL';
export const CLEAR_LOGOS_DATA_STATE = 'CLEAR LOGOS DATA STATE';
export const CLEAR_LOGO_ENTITY_STATE = 'CLEAR LOGO ENTITY STATE';
