export enum RequestName {
  GET_SVG_CATEGORIES = 'GET SVG CATEGORIES',
  GET_SVG_CATEGORY_ENTITY = 'GET SVG CATEGORY ENTITY',
  UPDATE_SVG_CATEGORY_ENTITY = 'UPDATE SVG CATEGORY ENTITY',
  CREATE_SVG_CATEGORY_ENTITY = 'CREATE SVG CATEGORY ENTITY',
  DELETE_SVG_CATEGORY_ENTITY = 'DELETE SVG CATEGORY ENTITY',
}

export type RequestError = {
  requestName: RequestName,
  error: string,
};

export type SVGCategoryData = {
  id?: number,
  name: string,
  type: string,
  order: number,
};

export type SVGCategoriesDataState = {
  svgcategories: SVGCategoryData[],
  details: SVGCategoryData | null,
  loadingRequests: RequestName[],
  requestErrors: RequestError[],
};

export const GET_SVG_CATEGORIES_REQUEST = 'GET SVG CATEGORIES REQUEST';
export const GET_SVG_CATEGORIES_SUCCESS = 'GET SVG CATEGORIES SUCCESS';
export const GET_SVG_CATEGORIES_FAIL = 'GET SVG CATEGORIES FAIL';
export const GET_SVG_CATEGORY_ENTITY_REQUEST = 'GET SVG CATEGORY ENTITY REQUEST';
export const GET_SVG_CATEGORY_ENTITY_SUCCESS = 'GET SVG CATEGORY ENTITY SUCCESS';
export const GET_SVG_CATEGORY_ENTITY_FAIL = 'GET SVG CATEGORY ENTITY FAIL';
export const UPDATE_SVG_CATEGORY_ENTITY_REQUEST = 'UPDATE SVG CATEGORY ENTITY REQUEST';
export const UPDATE_SVG_CATEGORY_ENTITY_SUCCESS = 'UPDATE SVG CATEGORY ENTITY SUCCESS';
export const UPDATE_SVG_CATEGORY_ENTITY_FAIL = 'UPDATE SVG CATEGORY ENTITY FAIL';
export const CREATE_SVG_CATEGORY_ENTITY_REQUEST = 'CREATE SVG CATEGORY ENTITY REQUEST';
export const CREATE_SVG_CATEGORY_ENTITY_SUCCESS = 'CREATE SVG CATEGORY ENTITY SUCCESS';
export const CREATE_SVG_CATEGORY_ENTITY_FAIL = 'CREATE SVG CATEGORY ENTITY FAIL';
export const DELETE_SVG_CATEGORY_ENTITY_REQUEST = 'DELETE SVG CATEGORY ENTITY REQUEST';
export const DELETE_SVG_CATEGORY_ENTITY_SUCCESS = 'DELETE SVG CATEGORY ENTITY SUCCESS';
export const DELETE_SVG_CATEGORY_ENTITY_FAIL = 'DELETE SVG CATEGORY ENTITY FAIL';
export const CLEAR_SVG_CATEGORIES_DATA_STATE = 'CLEAR SVG CATEGORIES DATA STATE';
export const CLEAR_SVG_CATEGORY_ENTITY_STATE = 'CLEAR SVG CATEGORY ENTITY STATE';
