export enum RequestName {
  GET_TEMPLATE_GROUPS = 'GET TEMPLATE GROUPS',
  GET_TEMPLATE_GROUP_ENTITY = 'GET TEMPLATE GROUP ENTITY',
  UPDATE_TEMPLATE_GROUP_ENTITY = 'UPDATE TEMPLATE GROUP ENTITY',
  CREATE_TEMPLATE_GROUP_ENTITY = 'CREATE TEMPLATE GROUP ENTITY',
  DELETE_TEMPLATE_GROUP_ENTITY = 'DELETE TEMPLATE GROUP ENTITY',
}

export type RequestError = {
  requestName: RequestName,
  error: string,
};

export type TemplateGroupData = {
  id?: number,
  name: string,
  productId: number,
};

export type TemplateGroupDataState = {
  products: TemplateGroupData[],
  details: TemplateGroupData | null,
  loadingRequests: RequestName[],
  requestErrors: RequestError[],
};

export const GET_TEMPLATE_GROUPS_REQUEST = 'GET TEMPLATE GROUPS REQUEST';
export const GET_TEMPLATE_GROUPS_SUCCESS = 'GET TEMPLATE GROUPS SUCCESS';
export const GET_TEMPLATE_GROUPS_FAIL = 'GET TEMPLATE GROUPS FAIL';
export const GET_TEMPLATE_GROUP_ENTITY_REQUEST = 'GET TEMPLATE GROUP ENTITY REQUEST';
export const GET_TEMPLATE_GROUP_ENTITY_SUCCESS = 'GET TEMPLATE GROUP ENTITY SUCCESS';
export const GET_TEMPLATE_GROUP_ENTITY_FAIL = 'GET TEMPLATE GROUP ENTITY FAIL';
export const UPDATE_TEMPLATE_GROUP_ENTITY_REQUEST = 'UPDATE TEMPLATE GROUP ENTITY REQUEST';
export const UPDATE_TEMPLATE_GROUP_ENTITY_SUCCESS = 'UPDATE TEMPLATE GROUP ENTITY SUCCESS';
export const UPDATE_TEMPLATE_GROUP_ENTITY_FAIL = 'UPDATE TEMPLATE GROUP ENTITY FAIL';
export const CREATE_TEMPLATE_GROUP_ENTITY_REQUEST = 'CREATE TEMPLATE GROUP ENTITY REQUEST';
export const CREATE_TEMPLATE_GROUP_ENTITY_SUCCESS = 'CREATE TEMPLATE GROUP ENTITY SUCCESS';
export const CREATE_TEMPLATE_GROUP_ENTITY_FAIL = 'CREATE TEMPLATE GROUP ENTITY FAIL';
export const DELETE_TEMPLATE_GROUP_ENTITY_REQUEST = 'DELETE TEMPLATE GROUP ENTITY REQUEST';
export const DELETE_TEMPLATE_GROUP_ENTITY_SUCCESS = 'DELETE TEMPLATE GROUP ENTITY SUCCESS';
export const DELETE_TEMPLATE_GROUP_ENTITY_FAIL = 'DELETE TEMPLATE GROUP ENTITY FAIL';
export const CLEAR_TEMPLATE_GROUPS_DATA_STATE = 'CLEAR TEMPLATE GROUPS DATA STATE';
export const CLEAR_TEMPLATE_GROUP_ENTITY_STATE = 'CLEAR TEMPLATE GROUP ENTITY STATE';
